
node1:
    environment:
        - SERVERNAME=node1
    build: ./node
    links:
        - redis
    ports:
        - "8080"
node2:
    environment:
        - SERVERNAME=node2
    build: ./node
    links:
        - redis
    ports:
        - "8080"
node3:
    environment:
        - SERVERNAME=node3
    build: ./node    
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"
nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"


        